[behave.formatters]
html = behave_html_formatter:HTMLFormatter

# Comenzi pentru rularea testelor:
# behave --tags=@Login_001 -f html -o reports/Login_001.html --no-capture  - Un singur scenariu
# behave features/B_FunctionalitatiGenerale.feature -f html -o reports/B_FunctionalitatiGenerale.html --no-capture - Un fisier .feature complet
# behave -f html -o reports/all_test.html --no-capture - toate testele

# Comenzi pentru rularea cu diferite browsere:
# behave -D browser=chrome -f html -o reports/all_test.html --no-capture - Google Chrome
# behave -D browser=firefox -f html -o reports/all_test.html --no-capture - Mozilla Firefox
# behave -D browser=edge -f html -o reports/all_test.html --no-capture - Microsoft Edge

# Comenzi instalare utilitare:
# pip install selenium
# pip install behave
# pip install behave-html-formatter
