[behave.formatters]
html = behave_html_formatter:HTMLFormatter

# Comenzi pentru rularea testelor:
# behave --tags=@Login_001 -f html -o reports/Login_001.html --no-capture  - Un singur scenariu
# behave features/B_FunctionalitatiGenerale.feature -f html -o reports/B_FunctionalitatiGenerale.html --no-capture - Un fisier .feature complet
# behave -f html -o reports/all_test.html --no-capture - toate testele



# pip install behave-html-formatter
